// ADHD-safe calm color palettes

export const themes = {
  calm: {
    name: 'Calm',
    bg: '#F7F6F3',
    surface: '#FFFFFF',
    surfaceHover: '#F0EFEC',
    primary: '#5B7B6F',
    primaryLight: '#8FADA0',
    accent: '#C4956A',
    text: '#2D3436',
    textSecondary: '#636E72',
    textMuted: '#B2BEC3',
    border: '#DFE6E9',
    success: '#6AB04C',
    warning: '#F0932B',
    danger: '#EB4D4B',
    energyLow: '#A8E6CF',
    energyMed: '#FFD93D',
    energyHigh: '#FF6B6B',
  },
  ocean: {
    name: 'Ocean',
    bg: '#EFF5F5',
    surface: '#FFFFFF',
    surfaceHover: '#E8F0F0',
    primary: '#3D7C98',
    primaryLight: '#7EB8CC',
    accent: '#D4A574',
    text: '#1A3A4A',
    textSecondary: '#4A6A7A',
    textMuted: '#9AB5C5',
    border: '#C5DAE5',
    success: '#6AB04C',
    warning: '#F0932B',
    danger: '#EB4D4B',
    energyLow: '#B5E8D5',
    energyMed: '#FFE066',
    energyHigh: '#FF7979',
  },
  forest: {
    name: 'Forest',
    bg: '#F0F4F0',
    surface: '#FFFFFF',
    surfaceHover: '#E8EDE8',
    primary: '#4A7C59',
    primaryLight: '#7DB08D',
    accent: '#C49A6C',
    text: '#1A2E1A',
    textSecondary: '#4A5E4A',
    textMuted: '#8FA88F',
    border: '#C5D5C5',
    success: '#6AB04C',
    warning: '#F0932B',
    danger: '#EB4D4B',
    energyLow: '#A8E6CF',
    energyMed: '#FFD93D',
    energyHigh: '#FF6B6B',
  },
  sunset: {
    name: 'Sunset',
    bg: '#FBF5F0',
    surface: '#FFFFFF',
    surfaceHover: '#F5ECE5',
    primary: '#B8605A',
    primaryLight: '#D4908A',
    accent: '#C49A6C',
    text: '#3D2520',
    textSecondary: '#7A5550',
    textMuted: '#C09A95',
    border: '#E5D0CB',
    success: '#6AB04C',
    warning: '#F0932B',
    danger: '#EB4D4B',
    energyLow: '#FFD8C8',
    energyMed: '#FFD93D',
    energyHigh: '#FF6B6B',
  },
  midnight: {
    name: 'Midnight',
    bg: '#1A1A2E',
    surface: '#252540',
    surfaceHover: '#2E2E50',
    primary: '#7B8CDE',
    primaryLight: '#A5B0E8',
    accent: '#D4A574',
    text: '#E8E8F0',
    textSecondary: '#A0A0B8',
    textMuted: '#606080',
    border: '#3A3A5A',
    success: '#6AB04C',
    warning: '#F0932B',
    danger: '#EB4D4B',
    energyLow: '#4A7A6A',
    energyMed: '#8A7A3A',
    energyHigh: '#8A4A4A',
  },
} as const;

export type ThemeName = keyof typeof themes;
export type ThemeColors = (typeof themes)[ThemeName];

export function getTheme(name: ThemeName): ThemeColors {
  return themes[name];
}
